### ISSUE TITLE
Minor Issues - Creative Tab, Schematic Table missing subtitle

### ISSUE THREAD

**Issue by MelodicCougar7** [ArsenicPurple/CreateArmsRace#2]
![image](https://github.com/user-attachments/assets/2bf60a23-bfbb-4025-90c4-eb353cdec452)
Creative tab doesn't have a name. Image is self explanatory.

![image](https://github.com/user-attachments/assets/2d49d97c-6073-4dc8-9809-7ce70479fa57)
Schematic Table has a missing subtitle.

**Comment by ArsenicPurple** [comment]
Thank you

**Comment by ArsenicPurple** [comment]
Fixed
